### ISSUE TITLE
Command-line flags

### ISSUE THREAD

**Issue by weierophinney** [bookdown/Bookdown.Bookdown#11] opened 2015-06-11 22:07 UTC
We're planning on using Bookdown for the documentation of the various Zend Framework components. One thing I'd like to be able to do is have a bare-minimum `bookdown.json` that specifies the title and content, and optionally the default target, and then specify the template (and possibly the target) via a command-line flag. This would allow us to have the "official" templates in a top-level repo that aggregates documentation from each of the components, but also allow developers to render the documentation using that template if it's checked out somewhere on their filesystem:

``` console
$ bookdown --template=../documentation/templates/main.php doc/bookdown.json
```

Or, to override the target:

``` console
$ bookdown \
> --template=../documentation/templates/main.php \
> --target=../documentation/html/ \
> doc/bookdown.json
```

**Comment by pmjones** [comment] 2015-06-13 18:49
/me nods

Given config file and option flag, which do you think should take precedence? (I'd say option flag.)

**Comment by weierophinney** [comment] 2015-06-13 18:51
Definitely option flag; that's the most specific, as it's specified at time
of invocation.

**Comment by pmjones** [comment] 2015-06-13 19:05
Agreed. Let me see what I can do. (Additionally, if you have time and inclination to work up a PR, I'll review it.)

**Comment by pmjones** [comment] 2015-06-14 15:58
This should be fixed; try the dev-develop branch and let me know how it goes for you.

**Comment by pmjones** [comment] 2015-06-14 16:20
Nope, not yet -- sorry for the noise.

**Comment by pmjones** [comment] 2015-06-14 17:26
@weierophinney OK, **now** try dev-develop. You should be able override with `--template=` and/or `--target=` at will.

**Comment by weierophinney** [comment] 2015-06-15 17:10
I can confirm it works... but there's one oddity. :)

So, I have a directory structure that has the following:

```
documentation/
    doc/
        templates/
a-component/
    doc/
        bookdown.json
        book/
```

Inside of `a-component/`, I invoked bookdown with the following:

``` console
$ bookdown --template=../documentation/doc/templates/main.php doc/bookdown.json
```

This failed; it could not find the template:

```
Cannot find template 'doc/../documentation/doc/templates/main.php'.
```

In other words, it was resolving the relative path relative to the `bookdown.json`, not where `bookdown` was actually invoked.

I would expect it to resolve the path based on where the script was invoked. This would require resolving path arguments prior to parsing the `bookdown.json`, probably.

(When I re-ran and specified the path relative to the `bookdown.json`, it worked perfectly.)

**Comment by pmjones** [comment] 2015-06-15 19:22
Mmm, I can guess what the problem is. I'll take a look.

**Comment by pmjones** [comment] 2015-06-15 20:30
OK @weierophinney give it another go. The relevant commit is https://github.com/bookdown/Bookdown.Bookdown/commit/dee1f4230a3e8a3b11b977ec4a131b848e19afbe and takes away the code to "fix" the path to make it relative to the bookdown.json file.

**Comment by weierophinney** [comment] 2015-06-15 20:34
Works perfectly, @pmjones ! :ship: !!!

**Comment by pmjones** [comment] 2015-06-15 20:35
Finally. Sorry for the hassle, and thanks for your patience. New release forthcoming as a result!

**Closed as completed by pmjones** 2015-06-15 20:35 UTC
